spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: false
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-3-234-169-147.compute-1.amazonaws.com:5432/d1us9cpbvbvli8?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&sslmode=require
    driver-class-name: org.postgresql.Driver
    username: unclxqcdblzmzk
    password: bb83623a9a0eae205d5db19637be54028543c95965a9ce7a66d81b05c1711f60
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5

logging:
  level:
    root: INFO
    org.springframework: ERROR
